/*******************************************************************************
 * Copyright 2015 Google Inc. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
package com.google.research.ic.ferret;

import com.google.research.ic.ferret.test.Debug;

import java.io.File;

import javax.swing.ImageIcon;

/**
 * TODO: Insert description here. (generated by marknewman)
 */
public class ResourceManager {

  public static final String DEFAULT_RESOURCE_DIR = "resources";

  public static final String EVENT_BACKGROUND_IMAGE_FILENAME = "EventBGBlueSmall.png";
  public static final String ARROW_IMAGE_FILENAME = "ArrowBlueSmall.png";
  public static final String RED_DOT_IMAGE_FILENAME = "RedDotSmall.png";
  public static final String SEARCH_ICON_IMAGE_FILENAME = "SearchIconSmall.png";
  
  
  private String resourceDir = DEFAULT_RESOURCE_DIR;
  private ImageIcon eventBackgroundImageIcon = null;
  private ImageIcon arrowImageIcon = null;
  private ImageIcon redDotImageIcon = null;
  private ImageIcon searchIconImageIcon = null;
   
  private static ResourceManager theHandler = null;
  
  public void loadResources() {

    String pathToResources = System.getProperty("user.dir") + File.separator +
        resourceDir + File.separator;

    eventBackgroundImageIcon = new ImageIcon(pathToResources + 
        EVENT_BACKGROUND_IMAGE_FILENAME);
    arrowImageIcon = new ImageIcon(pathToResources + 
        ARROW_IMAGE_FILENAME);
    redDotImageIcon = new ImageIcon(pathToResources + 
        RED_DOT_IMAGE_FILENAME);
    searchIconImageIcon = new ImageIcon(pathToResources + 
        SEARCH_ICON_IMAGE_FILENAME);
    Debug.log("Loaded image icons: " + eventBackgroundImageIcon.getIconWidth());
  }

  private ResourceManager() {  
  }
  
  public static ResourceManager getResourceManager() {
    if (theHandler == null) {
      theHandler = new ResourceManager();
    }
    return theHandler;
  }

  /**
   * @return the eventBackgroundImageIcon
   */
  public ImageIcon getEventBackgroundImageIcon() {
    return eventBackgroundImageIcon;
  }

  
  /**
   * @return the arrowImageIcon
   */
  public ImageIcon getArrowImageIcon() {
    return arrowImageIcon;
  }

  /**
   * @return the redDotImageIcon
   */
  public ImageIcon getRedDotImageIcon() {
    return redDotImageIcon;
  }

  /**
   * @return the searchIconImageIcon
   */
  public ImageIcon getSearchIconImageIcon() {
    return searchIconImageIcon;
  } 
  
  
}
