/*******************************************************************************
 * Copyright 2015 Google Inc. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
package com.google.research.ic.ferret.data;

import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonElement;
import com.google.research.ic.ferret.data.attributes.Attribute;

import java.io.BufferedOutputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.lang.reflect.Type;
import java.util.List;

/**
 * TODO: Insert description here. (generated by marknewman)
 */
public interface Parser {
  public List<Attribute> getAvailableAttributes();
  public List<Snippet> readLogDirectory(String logDir);
  public List<Snippet> readLogFile(String logFile);
  public List<Snippet> readDemoDirectory(String logDir);
  public Event parseEvent(String event);
  public boolean compressSnippet(Snippet s, boolean inspectWholeSnippet);

  public void writeSnippet(Snippet snip, File file);
  public void writeEvent(Event evt, File file);
  
  public Event deserializeEvent(JsonElement json, Type klass,
      JsonDeserializationContext jdContext);
}
