package com.google.research.ic.ferret.test;

import com.google.research.ic.ferret.data.Snippet;
import com.google.research.ic.ferret.data.SubSequence;

/**
 * TODO: Insert description here. (generated by marknewman)
 */
public class ResultRegion extends LabeledRegion {

  public SubSequence subS = null;
  
  public ResultRegion(LabeledRegion lr, SubSequence subS) {
    super(lr.sourceSnippet, lr.tag, lr.startIndex, lr.endIndex);
    this.subS = subS;
  }

  public String toString() {
    return super.toString() + " " + subS.toString();
  }
}

