package com.google.research.ic.ferret;

import java.awt.Color;
import java.awt.Dimension;

import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 * TODO: Insert description here. (generated by marknewman)
 */
public class ArrowPanel extends JPanel {

  private ImageIcon arrowIcon = null;
      
  public ArrowPanel() {
    arrowIcon = ResourceManager.getResourceManager().getArrowImageIcon();
    JLabel arrowLabel = new JLabel(arrowIcon);
    setBackground(Color.white);
    setOpaque(true);
    setPreferredSize(new Dimension(arrowIcon.getIconWidth(), 100));
    setLayout(new BoxLayout(this, BoxLayout.X_AXIS));
    add(arrowLabel);
  }
  
}
