package com.google.research.ic.ferret;

/**
 * TODO: Insert description here. (generated by marknewman)
 */
public interface Constants {
  public static final String IGNORE_SYSTEM_EVENTS = "IgnoreSystemEvents";
}
