package com.google.research.ic.ferret;

import com.google.research.ic.ferret.data.Event;

/**
 * TODO: Insert description here. (generated by marknewman)
 */
public interface DemoEventListener {

  public void onEventReceived(Event event);
}
