package com.google.research.ic.ferret;

import com.google.research.ic.ferret.data.ResultSet;
import com.google.research.ic.ferret.data.attributes.Bin;
import com.google.research.ic.ferret.test.Debug;

import java.awt.Dimension;
import java.util.List;
import java.util.Map;

import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 * TODO: Insert description here. (generated by marknewman)
 */
public class ResultSetSummaryPanel extends JPanel {

  
  public ResultSetSummaryPanel(ResultSet results) {
    Map <String, List<Bin>> summaries = results.getAttributeSummaries();
    
    setLayout(new BoxLayout(this, BoxLayout.Y_AXIS));
    // create summary panels
    JPanel summaryPanel = null;
    JLabel summaryLabel = null;
    
    Debug.log("Creating results panel. Summaries: " + summaries);
    
    for (String s : summaries.keySet() ) {
      List<Bin> sumBins = summaries.get(s);
      AttributeSummaryPanel attrSumPanel = new AttributeSummaryPanel(sumBins);
      add(attrSumPanel);
    }    
    setPreferredSize(new Dimension(400, 400));
  }
  
}
