package com.google.research.ic.ferret.test;

import com.google.research.ic.ferret.Config;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * TODO: Insert description here. (generated by marknewman)
 */
public class Debug {
  
  public static final String LOG_NAME = "qbdila";
  
  public static void log(String m) {
    if (Config.DEBUG) {
      Logger l = Logger.getLogger(LOG_NAME);
      l.info(m);
      l.setLevel(Level.INFO);
    }
  }
}
