package com.google.research.ic.ferret.data.attributes;

/**
 * TODO: Insert description here. (generated by marknewman)
 */
public interface Attribute {

  public String getKey();
  public Object getValue();
  public String getType();

}
