package com.google.research.ic.ferret.data.attributes;

import com.google.research.ic.ferret.data.ResultSet;
import com.google.research.ic.ferret.data.Snippet;

import java.util.List;

/**
 * TODO: Insert description here. (generated by marknewman)
 */
public interface AttributeHandler {

  /**
   * @param snippet
   */
  public void updateAttribute(Snippet snippet);

  public String getKey();  
  public String getKeyDisplayString(Attribute attribute);
  public String getValueDisplayString(Attribute attribute);
  
  public List<Bin> computeSummary(ResultSet set);   
  
}
