package com.google.research.ic.ferret.data.ext.alogger;

/**
 * TODO: Insert description here. (generated by marknewman)
 */
public class ALoggerDistanceWeights {

  public static float EVENT_TYPE_DIFFERENCE_WEIGHT_DEFAULT = Float.MAX_VALUE;
  public static float CLASS_NAME_DIFFERENCE_WEIGHT_DEFAULT = Float.MAX_VALUE;
  public static float PACKAGE_NAME_DIFFERENCE_WEIGHT_DEFAULT = Float.MAX_VALUE;
  public static float VIEW_HIERARCHY_DIFFERENCE_WEIGHT_DEFAULT = 100.0f;
  public static float WIDGET_TEXT_DIFFERENCE_WEIGHT_DEFAULT = 1.0f;
  
  private float eventTypeDifferenceWeight = EVENT_TYPE_DIFFERENCE_WEIGHT_DEFAULT;
  private float classNameDifferenceWeight = CLASS_NAME_DIFFERENCE_WEIGHT_DEFAULT;
  private float packageNameDifferenceWeight = PACKAGE_NAME_DIFFERENCE_WEIGHT_DEFAULT;
  private float viewHierarchyDifferenceWeight = VIEW_HIERARCHY_DIFFERENCE_WEIGHT_DEFAULT;
  private float widgetTextDifferenceWeight = WIDGET_TEXT_DIFFERENCE_WEIGHT_DEFAULT;
  

  public ALoggerDistanceWeights() {}

  /**
   * @param eventTypeDifferenceWeight
   * @param classNameDifferenceWeight
   * @param packageNamdDifferenceWeight
   * @param viewHierarchyDifferenceWeight
   * @param widgetTextDifferenceWeight
   */
  public ALoggerDistanceWeights(float eventTypeDifferenceWeight, float classNameDifferenceWeight,
      float packageNamdDifferenceWeight, float viewHierarchyDifferenceWeight,
      float widgetTextDifferenceWeight) {
    super();
    this.eventTypeDifferenceWeight = eventTypeDifferenceWeight;
    this.classNameDifferenceWeight = classNameDifferenceWeight;
    this.packageNameDifferenceWeight = packageNamdDifferenceWeight;
    this.viewHierarchyDifferenceWeight = viewHierarchyDifferenceWeight;
    this.widgetTextDifferenceWeight = widgetTextDifferenceWeight;
  }

  /**
   * @return the eventTypeDifferenceWeight
   */
  public float getEventTypeDifferenceWeight() {
    return eventTypeDifferenceWeight;
  }

  /**
   * @return the classNameDifferenceWeight
   */
  public float getClassNameDifferenceWeight() {
    return classNameDifferenceWeight;
  }

  /**
   * @return the packageNamdDifferenceWeight
   */
  public float getPackageNameDifferenceWeight() {
    return packageNameDifferenceWeight;
  }

  /**
   * @return the viewHierarchyDifferenceWeight
   */
  public float getViewHierarchyDifferenceWeight() {
    return viewHierarchyDifferenceWeight;
  }

  /**
   * @return the widgetTextDifferenceWeight
   */
  public float getWidgetTextDifferenceWeight() {
    return widgetTextDifferenceWeight;
  }
  
  
}
