package com.google.research.ic.ferret.data;

import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonElement;
import com.google.research.ic.ferret.data.attributes.Attribute;

import java.io.BufferedOutputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.lang.reflect.Type;
import java.util.List;

/**
 * TODO: Insert description here. (generated by marknewman)
 */
public interface Parser {
  public List<Attribute> getAvailableAttributes();
  public List<Snippet> readLogDirectory(String logDir);
  public List<Snippet> readLogFile(String logFile);
  public List<Snippet> readDemoDirectory(String logDir);
  public Event parseEvent(String event);

  public void writeSnippet(Snippet snip, File file);
  public void writeEvent(Event evt, File file);
  
  public Event deserializeEvent(JsonElement json, Type klass,
      JsonDeserializationContext jdContext);
}
