package com.google.research.ic.ferret.data;

/**
 * TODO: Insert description here. (generated by marknewman)
 */
public class RankedSnippet implements Comparable<RankedSnippet> {
  private Snippet snippet = null;
  private Float distance = -1.0f;
  /**
   * @param snippet
   * @param distance
   */
  public RankedSnippet(Snippet snippet, Float distance) {
    super();
    this.snippet = snippet;
    this.distance = distance;
  }
  /**
   * @return the snippet
   */
  public Snippet getSnippet() {
    return snippet;
  }
  /**
   * @param snippet the snippet to set
   */
  public void setSnippet(Snippet snippet) {
    this.snippet = snippet;
  }
  /**
   * @return the distance
   */
  public Float getDistance() {
    return distance;
  }
  /**
   * @param distance the distance to set
   */
  public void setDistance(Float distance) {
    this.distance = distance;
  }
  
  @Override
  public int compareTo(RankedSnippet other) {
    return Float.compare(distance, other.distance);
  }  
  
  @Override
  public String toString() {
    return snippet.toString() + "\nDISTANCE = " + distance;
  }
}
