package com.google.research.ic.ferret.data;



/**
 * TODO: Insert description here. (generated by marknewman)
 */
public class UberResultSet {

  private ResultSet closeMatches = null;
  private ResultSet weakMatches = null;
  private ResultSet compressedMatches = null;
  private ResultSet elongatedMatches = null;
  private ResultSet startMatches = null;
  private ResultSet endMatches = null;
  private ResultSet middleMatches = null;

  public ResultSet getCloseMatches() {
    return closeMatches;
  }
  
  public void setCloseMatches(ResultSet closeMatches) {
    this.closeMatches = closeMatches;
  }
  
  public ResultSet getWeakMatches() {
    return weakMatches;
  }
  
  public void setWeakMatches(ResultSet weakMatches) {
    this.weakMatches = weakMatches;
  }
  
  public ResultSet getCompressedMatches() {
    return compressedMatches;
  }
  
  public void setCompressedMatches(ResultSet compressedMatches) {
    this.compressedMatches = compressedMatches;
  }
  
  public ResultSet getElongatedMatches() {
    return elongatedMatches;
  }
  
  public void setElongatedMatches(ResultSet elongatedMatches) {
    this.elongatedMatches = elongatedMatches;
  }
  
  public ResultSet getStartMatches() {
    return startMatches;
  }
  
  public void setStartMatches(ResultSet startMatches) {
    this.startMatches = startMatches;
  }
  
  public ResultSet getEndMatches() {
    return endMatches;
  }
  
  public void setEndMatches(ResultSet endMatches) {
    this.endMatches = endMatches;
  }
  
  public ResultSet getMiddleMatches() {
    return middleMatches;
  }
  
  public void setMiddleMatches(ResultSet middleMatches) {
    this.middleMatches = middleMatches;
  }

}



