/*******************************************************************************
 * Copyright 2015 Google Inc. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
package com.google.research.ic.ferret.data;



/**
 * TODO: Insert description here. (generated by marknewman)
 */
public class UberResultSet {

  private ResultSet closeMatches = null;
  private ResultSet weakMatches = null;
  private ResultSet compressedMatches = null;
  private ResultSet elongatedMatches = null;
  private ResultSet startMatches = null;
  private ResultSet endMatches = null;
  private ResultSet middleMatches = null;

  public ResultSet getCloseMatches() {
    return closeMatches;
  }
  
  public void setCloseMatches(ResultSet closeMatches) {
    this.closeMatches = closeMatches;
  }
  
  public ResultSet getWeakMatches() {
    return weakMatches;
  }
  
  public void setWeakMatches(ResultSet weakMatches) {
    this.weakMatches = weakMatches;
  }
  
  public ResultSet getCompressedMatches() {
    return compressedMatches;
  }
  
  public void setCompressedMatches(ResultSet compressedMatches) {
    this.compressedMatches = compressedMatches;
  }
  
  public ResultSet getElongatedMatches() {
    return elongatedMatches;
  }
  
  public void setElongatedMatches(ResultSet elongatedMatches) {
    this.elongatedMatches = elongatedMatches;
  }
  
  public ResultSet getStartMatches() {
    return startMatches;
  }
  
  public void setStartMatches(ResultSet startMatches) {
    this.startMatches = startMatches;
  }
  
  public ResultSet getEndMatches() {
    return endMatches;
  }
  
  public void setEndMatches(ResultSet endMatches) {
    this.endMatches = endMatches;
  }
  
  public ResultSet getMiddleMatches() {
    return middleMatches;
  }
  
  public void setMiddleMatches(ResultSet middleMatches) {
    this.middleMatches = middleMatches;
  }

}



