/*******************************************************************************
 * Copyright 2015 Google Inc. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
package com.google.research.ic.ferret.data.ext.alogger;

/**
 * TODO: Insert description here. (generated by marknewman)
 */
public class ALoggerDistanceWeights {

  public static float EVENT_TYPE_DIFFERENCE_WEIGHT_DEFAULT = Float.MAX_VALUE;
  public static float CLASS_NAME_DIFFERENCE_WEIGHT_DEFAULT = Float.MAX_VALUE;
  public static float PACKAGE_NAME_DIFFERENCE_WEIGHT_DEFAULT = Float.MAX_VALUE;
  public static float VIEW_HIERARCHY_DIFFERENCE_WEIGHT_DEFAULT = 100.0f;
  public static float WIDGET_TEXT_DIFFERENCE_WEIGHT_DEFAULT = 1.0f;
  
  private float eventTypeDifferenceWeight = EVENT_TYPE_DIFFERENCE_WEIGHT_DEFAULT;
  private float classNameDifferenceWeight = CLASS_NAME_DIFFERENCE_WEIGHT_DEFAULT;
  private float packageNameDifferenceWeight = PACKAGE_NAME_DIFFERENCE_WEIGHT_DEFAULT;
  private float viewHierarchyDifferenceWeight = VIEW_HIERARCHY_DIFFERENCE_WEIGHT_DEFAULT;
  private float widgetTextDifferenceWeight = WIDGET_TEXT_DIFFERENCE_WEIGHT_DEFAULT;
  

  public ALoggerDistanceWeights() {}

  /**
   * @param eventTypeDifferenceWeight
   * @param classNameDifferenceWeight
   * @param packageNamdDifferenceWeight
   * @param viewHierarchyDifferenceWeight
   * @param widgetTextDifferenceWeight
   */
  public ALoggerDistanceWeights(float eventTypeDifferenceWeight, float classNameDifferenceWeight,
      float packageNamdDifferenceWeight, float viewHierarchyDifferenceWeight,
      float widgetTextDifferenceWeight) {
    super();
    this.eventTypeDifferenceWeight = eventTypeDifferenceWeight;
    this.classNameDifferenceWeight = classNameDifferenceWeight;
    this.packageNameDifferenceWeight = packageNamdDifferenceWeight;
    this.viewHierarchyDifferenceWeight = viewHierarchyDifferenceWeight;
    this.widgetTextDifferenceWeight = widgetTextDifferenceWeight;
  }

  /**
   * @return the eventTypeDifferenceWeight
   */
  public float getEventTypeDifferenceWeight() {
    return eventTypeDifferenceWeight;
  }

  /**
   * @return the classNameDifferenceWeight
   */
  public float getClassNameDifferenceWeight() {
    return classNameDifferenceWeight;
  }

  /**
   * @return the packageNamdDifferenceWeight
   */
  public float getPackageNameDifferenceWeight() {
    return packageNameDifferenceWeight;
  }

  /**
   * @return the viewHierarchyDifferenceWeight
   */
  public float getViewHierarchyDifferenceWeight() {
    return viewHierarchyDifferenceWeight;
  }

  /**
   * @return the widgetTextDifferenceWeight
   */
  public float getWidgetTextDifferenceWeight() {
    return widgetTextDifferenceWeight;
  }
  
  
}
